apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
      - name: myapp
        image: sehaj07/yourapp:da6d502b36b604d2eec96e7752e1fb31ef08bc13
        ports:
        - containerPort: 3000